### ISSUE TITLE
Investigar que es Circuit Breaker y aplicar a Traefik

### ISSUE THREAD

**Issue by XxRaXoRxX** [j0k3rD/real_time_chat_project#23]
- Programar evitando llamadas entre ms con Cache en Redis.
- Programar reintentos para saber si un ms está down.
- Escalar a dos un microservicio, y verificar cual esta down e ir redireccionado según funcionen

**Comment by NKAmazing** [comment]
Vamos a utilizar pycircuitbreaker para aplicar el patron de diseño Circuit Breaker en nuestro proyecto Python Django. 
https://pypi.org/project/pycircuitbreaker/ --> Implementacion del patron
Especificamente utilizaremos dos caracteristicas:
             - db_breaker: se utiliza para gestionar circuit breakers en vistas que acceden a la base de datos o en cualquier otro código que involucre interacciones con servicios externos o dependencias remotas
             - circuit:  es un decorador más general que se puede usar en cualquier función o método en Python para implementar un circuit breaker

**Comment by j0k3rD** [comment]
Documentacion que ver para cache en Django: 
https://docs.djangoproject.com/en/4.2/topics/cache/#redis
 - Ver si se implementa en Traefik
